export default {
  login: 'ChitThetAung',
  id: 42133389,
  node_id: 'MDQ6VXNlcjQyMTMzMzg5',
  avatar_url: "https://avatars2.githubusercontent.com/u/62891861?v=4",
  gravatar_id: '',
  url: 'https://api.github.com/users/ChitThetAung',
  html_url: "https://github.com/ChitThetAung",
  followers_url: 'https://api.github.com/users/john-smilga/followers',
  following_url:
    'https://api.github.com/users/john-smilga/following{/other_user}',
  gists_url: 'https://api.github.com/users/john-smilga/gists{/gist_id}',
  starred_url:
    'https://api.github.com/users/john-smilga/starred{/owner}{/repo}',
  subscriptions_url: 'https://api.github.com/users/john-smilga/subscriptions',
  organizations_url: 'https://api.github.com/users/john-smilga/orgs',
  repos_url: 'https://api.github.com/users/john-smilga/repos',
  events_url: 'https://api.github.com/users/john-smilga/events{/privacy}',
  received_events_url:
    'https://api.github.com/users/john-smilga/received_events',
  type: 'User',
  site_admin: false,
  name: 'Chit Thet Aung',
  company: 'You Tube',
  blog: 'www.github.com/chitthetaung',
  location: 'Yangon',
  email: null,
  hireable: null,
  bio: 'Creator of clone github',
  twitter_username: '@chitthetaung',
  public_repos: 152,
  public_gists: 20,
  followers: 1495,
  following: 40,
  created_at: '2018-08-06T06:48:23Z',
  updated_at: '2021-01-08T05:01:32Z',
};
